---
- name: Install OS Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
  when: ansible_distribution_version is version('8', '<')

- name: Install OS Packages for Centos >= 8
  yum: name={{ item }} state=present
  with_items:
    - python3-libselinux
  when: ansible_distribution_version is version('8', '>=')

- include_tasks: tarball.yml

- include_tasks: upstart.yml
  tags:
    - deploy

- include_tasks: systemd.yml
  tags:
    - deploy
