---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Populate service facts
    service_facts:
  - name: Example assertion 1
    assert:
      that: '"running" in ansible_facts["services"]["zookeeper.service"]["state"]'
      fail_msg: "Zookeeper don't running"
